name: Authenticate to Tailscale API
description: Issues a short-lived Tailscale API token for the workflow using its GitHub Actions OIDC identity.

inputs:
  client-id:
    description: OAuth client ID of the trust credential
    required: true
  audience:
    description: Audience value assigned to the trust credential
    required: true

outputs:
  access-token:
    description: Short-lived bearer token for the Tailscale API
    value: ${{ steps.exchange-token.outputs.access-token }}

runs:
  using: composite
  steps:
    - name: Check permissions
      run: |
        if [ -z "$ACTIONS_ID_TOKEN_REQUEST_URL" ] || [ -z "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]; then
          echo "::error title=$X_GITHUB_ACTION_REPOSITORY::Missing OIDC environment variables. Ensure 'id-token: write' permission is set for this job."
          exit 1
        fi
      shell: bash
      env:
        X_GITHUB_ACTION_REPOSITORY: ${{ github.action_repository }}

    - name: Check inputs
      if: inputs.audience == '' || inputs.client-id == ''
      run: |
        echo "::error title=$X_GITHUB_ACTION_REPOSITORY::Missing required inputs. Ensure 'audience' and 'client-id' are provided."
        exit 1
      shell: bash
      env:
        X_GITHUB_ACTION_REPOSITORY: ${{ github.action_repository }}

    - name: Get ID token
      id: get-id-token
      run: |
        set -u
        id_token=$(curl -fsSL --max-time 30 \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$OIDC_AUDIENCE" \
          -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN"  \
          | jq --raw-output --exit-status '.value')
        echo "::add-mask::$id_token"
        echo "id-token=$id_token" >> "$GITHUB_OUTPUT"
        echo "Obtained ID token."
      shell: bash
      env:
        OIDC_AUDIENCE: ${{ inputs.audience }}

    - name: Exchange token
      id: exchange-token
      run: |
        set -u
        access_token=$(curl -fsSL --max-time 30 \
          https://api.tailscale.com/api/v2/oauth/token-exchange \
          -d "client_id=$OIDC_CLIENT_ID" \
          -d "jwt=$OIDC_ID_TOKEN" \
          | jq --raw-output --exit-status '.access_token')
        echo "::add-mask::$access_token"
        echo "access-token=$access_token" >> "$GITHUB_OUTPUT"
        echo "Exchanged ID token for access token."
      shell: bash
      env:
        OIDC_CLIENT_ID: ${{ inputs.client-id }}
        OIDC_ID_TOKEN: ${{ steps.get-id-token.outputs.id-token }}
